### ISSUE TITLE
[BUG] - Nodes remain uninitialized --> CCM complains about "providerID cannot be an empty string"

### ISSUE THREAD

**Issue by kgeipel-retail7** [vultr/docker-machine-driver-vultr#36] opened 2023-12-19 12:13 UTC
After creating a cluster with one or more node pools, the nodes in the pools keep the taint "node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule" and therefor are not usable for normal workloads without taint toleration.

Also, the deployed Vultr CCM can not create a new Load Balancer due to the fact that it misses a ProviderID.

By searching for a solution for the first issue I stumbled upon some similar cases on vSphere and OpenStack clusters, where in both cases it seemed that the Docker Machine Driver which was used, did not return the required ProviderID.

**Rancher v2.5.9**
**K8s: v1.20.11**
**Vultr Docker Machine Driver v1.2.0**
**Vultr CCM v0.10.0**

**Used RKE Template:**
[vultr_rke_template.yml.json](https://github.com/vultr/docker-machine-driver-vultr/files/13715560/vultr_rke_template.yml.json)

**Used Node Template:**
[vultr_node_template.json](https://github.com/vultr/docker-machine-driver-vultr/files/13715564/vultr_node_template.json)

**EDIT**

found on another Node from a different provider the following k/v in the node spec
`providerId": "digitalocean://379349108",`

So this is simply missing on the Vultr Nodes.
![image](https://github.com/vultr/docker-machine-driver-vultr/assets/76164810/249e675a-e706-4e90-9f34-1865e96374c2)

See also:
[here](https://github.com/rancher/rke/issues/2400)

**Comment by happytreees** [comment] 2023-12-19 15:30
Hello @kgeipel-retail7 

Thank you for reporting this! The Vultr-CCM is primarily used for VKE and requires the providerID which is essentially just the Instance UUID of the machine so that it can quickly locate it. Unfortunately, docker-machine is not just for rancher/k8s so it does not have the ability to add labels to nodes. 

We can review adding the ability of the CCM to allow for usage without providerID labels, however, this would mean that it would have to operate off the node name so it would be logical to add a UID into the name of the machine to ensure duplicate labels do not cause issues with the CCM.

**Comment by kgeipel-retail7** [comment] 2023-12-20 06:35
Hi @happytreees thanks for the fast reply, the CCM is only one story, but the issue with the missing providerID is mainly that all nodes, which were provisioned using the docker-machine-driver, get a "NoSchedule" taint which must be removed manually and kills the advantage of autoscaling node pools.

![image](https://github.com/vultr/docker-machine-driver-vultr/assets/76164810/db16e2f0-1a8f-47bc-824f-5d53f82e957d)

Maybe you can check [that driver](https://github.com/JonasProgrammer/docker-machine-driver-hetzner/tree/master/driver), which was build for another hoster, to see how they solved it.

They also use the official docker-machine packages (github.com/docker/machine)

One additional hint, the providerID is not a label, it is an own k/v pair in the node spec, you can check that in the attached node definition:
[example_node.json](https://github.com/vultr/docker-machine-driver-vultr/files/13723841/example_node.json)

> the providerID which is essentially just the Instance UUID of the machine
And it has to have a prefix containing the provider name, in case of vultr it should be something like vultr://<UUID>

**Comment by happytreees** [comment] 2023-12-20 11:34
Hello @kgeipel-retail7 

I believe there is some misunderstandings from my comment. I'm fully aware of how the ProviderID should be constructed and the statement that it's just UUID is correct as the "vultr://" is more of an indicator for the provider(us) parsing it so we ensure the correct value is present. 

Additionally, when I stated usage without the providerid that was meant for initial lookup in the CCM when the instance joins the cluster. When a node joins it attempts to register with the CCM and when the lookup is completed successfully the taint is removed. At this time we set the providerID in the kubelet config for VKE so there was not a reason to lookup by name or set the providerID in the metadata. This is no longer the case due to clusters such as Rancher so it is something we would want to extend the capability for.

**Comment by happytreees** [comment] 2023-12-20 13:06
@kgeipel-retail7 

I don't have an estimated timeline but it also doesn't look difficult to do either. I will work on it this week. 

I am going to close this issue, however, if you want you can open an issue on our CCM repo and I can update that once the PR is in to add that. 

https://github.com/vultr/vultr-cloud-controller-manager/tree/master

**Comment by happytreees** [comment] 2023-12-20 15:38
@kgeipel-retail7 Can you share which version of the CCM you are using?

I reviewed the code and saw that I inadvertently added this ability to the CCM awhile back for a different issue, however, the functionality is there. You can see in this function that if the providerID is blank then it looks it up using the name and it's also set in the metadata:
https://github.com/vultr/vultr-cloud-controller-manager/blob/master/vultr/instancesv2.go#L123

I went ahead and deployed an RKE1 cluster using this driver and added the CCM as an external cloud provider. Once the nodes were up I ran into a small hiccup where the CCM required the instances to be attached to a VPC for the internal IP, however, once attached the CCM added the labels and providerID without any issues. I confirmed by reviewing the node itself and the providerID and vultr labels were present. 

As long as you use the newest version of the CCM v0.10.0 and ensure the instances get attached to a VPC(you can specify the VPC within the node template in rancher) then everything should come up without issue. 

In the new year I'm going to be adding the addons yaml to this directory to allow for the CCM, CSI to be added simply, but it is not present at this time.

**Closed by happytreees** 2023-12-20 15:38 UTC
Labels: bug

**Comment by kgeipel-retail7** [comment] 2023-12-21 07:15
Hi @happytreees as written above we are using the latest version **Vultr CCM v0.10.0** attaching a VPC to the nodes did the trick, now everything works like expected.

Only one small issue still exists with the CCM, in [CCM deployment file](https://raw.githubusercontent.com/vultr/vultr-cloud-controller-manager/master/docs/releases/v0.10.0.yml) there is a node scheduling rule which doesn't match any node in the cluster, since RKE clusters have no node annotation/label or taint **"node-role.kubernetes.io/master"**

So as a workaround, i simply cloned the workload as of type deployment and removed the scheduling rule.
